name: Run tests

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run_linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --respect-gitignore --extend-select W,N --output-format=github .
